variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - test
  - release
  - deploy

build-frontend-code-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-frontend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true  

include:
  - template: Security/SAST.gitlab-ci.yml 

spotbugs-sast:
  stage: test
  artifacts:
    reports:
       sast: gl-sast-report.json


sonarqube-frontend-sast:
  stage: test
  script: 
    - >
      cd frontend

      sonar-scanner
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_MOMO_FRONT}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_MOMO_FRONT}
      -Dsonar.projectName=${SONAR_POJECT_NAME_MOMO_FRONT}
      -Dsonar.sources=.
  needs:
    - build-frontend-code-job
  image: sonarsource/sonar-scanner-cli:10.0
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache

upload-frontend-release:
  stage: release
  needs:
    - build-frontend-code-job
    - sonarqube-frontend-sast
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/momo-store-frontend:$CI_COMMIT_SHA $CI_COMMIT_SHA

deploy-frontend-release-prod:
  stage: deploy
  needs:
    - upload-frontend-release
  image: dtzar/helm-kubectl:3.15.2
  before_script:  
    - mkdir ~/.kube
    - touch ~/.kube/config; touch ~/.kube/ca.pem
    - echo "$KUBE_CONFIG" >> ~/.kube/config  
    - echo "$KUBE_CONFIG_CA_PEM" >> ~/.kube/ca.pem
    - kubectl config use-context default
  script:
    - >
      helm upgrade --atomic --install frontend ./helm/frontend/ \
        --namespace ns \
        --set image.repository=${CI_REGISTRY_IMAGE}/momo-store-frontend \
        --set dockerconfigjson=${DOCKER_CONFIG_JSON} \
        --set image.tag=${CI_COMMIT_SHA}
    - rm ~/.kube/config
    - rm ~/.kube/ca.pem
    - echo "frontend is deployed via helm"
  rules: 
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual

deploy-frontend-release-dev:
  stage: deploy
  needs:
    - upload-frontend-release
  image: dtzar/helm-kubectl:3.15.2
  before_script:  
    - mkdir ~/.kube
    - touch ~/.kube/config; touch ~/.kube/ca.pem
    - echo "$KUBE_CONFIG" >> ~/.kube/config  
    - echo "$KUBE_CONFIG_CA_PEM" >> ~/.kube/ca.pem
    - kubectl config use-context default
  script:
    - >
      helm upgrade --atomic --install frontend ./helm/frontend/ \
        --namespace dev \
        --set image.repository=${CI_REGISTRY_IMAGE}/momo-store-frontend \
        --set dockerconfigjson=${DOCKER_CONFIG_JSON} \
        --set image.tag=${CI_COMMIT_SHA} \
        --set host="devel.std-025-02-momo-store.ru"
    - rm ~/.kube/config
    - rm ~/.kube/ca.pem
    - echo "frontend is deployed via helm"
  rules: 
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual

