---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: k8s-secret
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        - path: /products
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: {{ .Values.containerPort }}
        - path: /categories
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: {{ .Values.containerPort }}
        - path: /orders
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: {{ .Values.containerPort }}
        - path: /metrics
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: {{ .Values.containerPort }}
        - path: /auth/whoami
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: {{ .Values.containerPort }}
