---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: k8s-secret
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
{{- range $path := .Values.paths }}
        - path: {{ $path }}
          pathType: Prefix
          backend:
            service:
              name: {{ $.Chart.Name }}
              port:
                number: {{ $.Values.containerPort }}
{{- end }}
