---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret-backend
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: >-
          ${DOCKER_CONFIG_JSON}
type: kubernetes.io/dockerconfigjson
