variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - test
  - release

build-backend-code-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-backend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true  

include:
  - template: Security/SAST.gitlab-ci.yml 

spotbugs-sast:
  stage: test
  artifacts:
    reports:
       sast: gl-sast-report.json

test-backend:
  stage: test
  image: golang:1.22.4-alpine
  script:
    - cd backend
    - go test -v ./...
  only:
    changes:
      - backend/**/*
  dependencies:
    - build-backend-code-job

sonarqube-backend-sast:
  stage: test
  script: 
    - >
      cd backend

      sonar-scanner
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_MOMO_BACK}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_MOMO_BACK}
      -Dsonar.projectName=${SONAR_POJECT_NAME_MOMO_BACK}
      -Dsonar.sources=.
  needs:
    - build-backend-code-job
  image: sonarsource/sonar-scanner-cli:10.0
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache

upload-backend-release:
  stage: release
  needs:
    - build-backend-code-job
    - sonarqube-backend-sast
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/momo-store-backend:$CI_COMMIT_SHA $CI_COMMIT_SHA