---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |-
    worker_processes 1;
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen {{ .Values.containerPort }};
      
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.html;
          try_files $uri $uri/ /index.html;
        }
      
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        
        location ~ ^/(categories|products|auth|metrics|orders)/ {
            proxy_pass http://backend:8081;
        }
      }
    }
