---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret-frontend
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | quote }}
type: kubernetes.io/dockerconfigjson
