image:
  repository: ${CI_REGISTRY_IMAGE}/momo-store-backend
  pullPolicy: Always
  tag: ${CI_COMMIT_SHA}
replicas: 2
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
rollingUpdate:
  maxUnavailable: 2
  maxSurge: 20%
containerPort: 8081
resources:
  limits:
    cpu: "0.2"  
    memory: "2Gi" 
  requests:
    cpu: "0.1"  
    memory: "256Mi"
host: std-025-02-momo-store.ru
