image:
  repository: ${CI_REGISTRY_IMAGE}/momo-store-backend
  pullPolicy: Always
  tag: ${CI_COMMIT_SHA}
replicas: 2
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
rollingUpdate:
  maxUnavailable: 2
  maxSurge: 20%
containerPort: 8081

