image:
  repository: ${CI_REGISTRY_IMAGE}/momo-store-frontend
  pullPolicy: Always
  tag: ${CI_COMMIT_SHA}
replicas: 1
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
containerPort: 80
host: std-025-02-momo-store.ru
